name: publish-package-gh

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Build and Publish to GH
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure .npmrc
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'

      - name: Perform basic audit
        run: npm audit --audit-level low

      - name: Install dependencies
        run: npm ci

      - name: Publish
        run: |
          npm run build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
